#!/usr/bin/env python3
"""Generate the repository's Base typography layer from literal Base specs.

The generated CSS is the single formatting source for Base role, size, grid,
line-height, mono, and link semantics. It is intentionally derived from
`typography-spec.json`, not hand-tuned page by page.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SPEC=ROOT/'fern/data/design-systems/base-web/typography-spec.json'
OUT=ROOT/'fern/base-typography.css'
def pair(value): return f'{value[0]}px/{value[1]}px'
def main():
 s=json.loads(SPEC.read_text())
 css=f'''/* GENERATED by scripts/apply_base_typography.py — do not hand-edit.\n   Source: {SPEC.relative_to(ROOT)} */
:root {{
  --base-grid: {s['baseline_grid_px']}px;
  --base-font-display: "Uber Move", "Geist Sans", "Public Sans", system-ui, sans-serif;
  --base-font-text: "Uber Move Text", "Geist Sans", "Public Sans", system-ui, sans-serif;
  --base-font-mono: "Uber Move Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
  --base-display-xsmall: {pair(s['display']['xsmall'])};
  --base-display-small: {pair(s['display']['small'])};
  --base-display-medium: {pair(s['display']['medium'])};
  --base-display-large: {pair(s['display']['large'])};
  --base-heading-xsmall: {pair(s['heading']['xsmall'])};
  --base-heading-small: {pair(s['heading']['small'])};
  --base-heading-medium: {pair(s['heading']['medium'])};
  --base-heading-large: {pair(s['heading']['large'])};
  --base-heading-xlarge: {pair(s['heading']['xlarge'])};
  --base-heading-xxlarge: {pair(s['heading']['xxlarge'])};
  --base-label-xsmall: {pair(s['label']['xsmall'])};
  --base-label-small: {pair(s['label']['small'])};
  --base-label-medium: {pair(s['label']['medium'])};
  --base-label-large: {pair(s['label']['large'])};
  --base-paragraph-xsmall: {pair(s['paragraph']['xsmall'])};
  --base-paragraph-small: {pair(s['paragraph']['small'])};
  --base-paragraph-medium: {pair(s['paragraph']['medium'])};
  --base-paragraph-large: {pair(s['paragraph']['large'])};
}}

/* Base roles */
.fern-page-content {{ font-family: var(--base-font-text); }}
.fern-page-content h1, .base-heading-xxlarge {{ font-family: var(--base-font-display); font: 700 var(--base-heading-xxlarge) var(--base-font-display); letter-spacing: 0; }}
.fern-page-content h2, .base-heading-xlarge {{ font-family: var(--base-font-display); font: 700 var(--base-heading-xlarge) var(--base-font-display); letter-spacing: 0; }}
.fern-page-content h3, .base-heading-large {{ font-family: var(--base-font-display); font: 700 var(--base-heading-large) var(--base-font-display); letter-spacing: 0; }}
.fern-page-content h4, .base-heading-medium {{ font-family: var(--base-font-display); font: 700 var(--base-heading-medium) var(--base-font-display); letter-spacing: 0; }}
.base-display-xsmall {{ font: 700 var(--base-display-xsmall) var(--base-font-display); }}
.base-display-small {{ font: 700 var(--base-display-small) var(--base-font-display); }}
.base-display-medium {{ font: 700 var(--base-display-medium) var(--base-font-display); }}
.base-display-large {{ font: 700 var(--base-display-large) var(--base-font-display); }}
.base-label-xsmall {{ font: 500 var(--base-label-xsmall) var(--base-font-text); }}
.base-label-small {{ font: 500 var(--base-label-small) var(--base-font-text); }}
.base-label-medium {{ font: 500 var(--base-label-medium) var(--base-font-text); }}
.base-label-large {{ font: 500 var(--base-label-large) var(--base-font-text); }}
.fern-page-content p, .base-paragraph-medium {{ font: 400 var(--base-paragraph-medium) var(--base-font-text); }}
.base-paragraph-large {{ font: 400 var(--base-paragraph-large) var(--base-font-text); }}
.base-paragraph-small {{ font: 400 var(--base-paragraph-small) var(--base-font-text); }}
.base-paragraph-xsmall {{ font: 400 var(--base-paragraph-xsmall) var(--base-font-text); }}
.base-mono {{ font-family: var(--base-font-mono); font-variant-numeric: tabular-nums; }}

/* Base's 4px baseline is the only spacing unit used by role primitives. */
.fern-page-content :where(h1,h2,h3,h4,p) {{ margin-block-start: calc(var(--base-grid) * 6); margin-block-end: calc(var(--base-grid) * 4); }}
.fern-page-content p + p {{ margin-block-start: calc(var(--base-grid) * 4); }}
.fern-page-content p a {{ text-decoration: underline; text-underline-offset: 2px; }}

@media (max-width: 640px) {{
  .fern-page-content h1, .base-heading-xxlarge {{ font: 700 var(--base-heading-xlarge) var(--base-font-display); }}
  .fern-page-content h2, .base-heading-xlarge {{ font: 700 var(--base-heading-large) var(--base-font-display); }}
  .fern-page-content h3, .base-heading-large {{ font: 700 var(--base-heading-medium) var(--base-font-display); }}
}}
'''
 OUT.write_text(css)
 print(f'Wrote {{OUT.relative_to(ROOT)}} from literal Uber Base typography spec')
if __name__=='__main__':main()
